name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Kubernetes context
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: YourClusterName
        resource-group: YourResourceGroupName

    - name: Deploy to AKS
      run: |
        kubectl apply -f deployment.yaml
        if [ "${{ github.ref }}" == "refs/heads/stage" ] || [ "${{ github.ref }}" == "refs/heads/performance" ]; then
          kubectl apply -f hpa.yaml
        fi

    - name: Verify deployment
      run: kubectl rollout status deployment/my-application
